### ISSUE TITLE
Can't run Roboletric on windows: java.lang.NoSuchMethodException: android.os.Looper.<init>(boolean)

### ISSUE THREAD

**Issue by andr3medeiros** [nenick/AndroidStudioAndRobolectric#15]
I don't know if this issue happens only at windows, but as I just run the the project as it is, and got the issue plus, no other related issue was filed, I guess it could be.

I just ran RobolectricTest (right click) and got:

``` java
 java.lang.RuntimeException: java.lang.NoSuchMethodException: android.os.Looper.<init>(boolean)
    at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:233)
    at org.robolectric.shadows.ShadowLooper.createLooper(ShadowLooper.java:43)
    at org.robolectric.shadows.ShadowLooper.access$000(ShadowLooper.java:25)
    at org.robolectric.shadows.ShadowLooper$1.create(ShadowLooper.java:37) ... 
```

**Comment by andr3medeiros** [comment]
I just found out. In my maven settings.xml I added (as specified in [maven site](https://maven.apache.org/settings.html)):

```
<localRepository>${user.home}/.m2/repository</localRepository>
```

After remove it, Roboletric worked fine.

**Comment by nenick** [comment]
Great, thanks for reporting.
