### ISSUE TITLE
No issue ( java.lang.StringIndexOutOfBoundsException: String index out of range: -9)

### ISSUE THREAD

**Issue by misrakli** [nenick/AndroidStudioAndRobolectric#20]
I added a very simple activity with a very simple layout and i get following exception when running the test.

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -9
at java.lang.String.substring(String.java:1954)
at org.robolectric.res.ResName.qualifyResName(ResName.java:51)
at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getParent(ShadowAssetManager.java:466)
at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getAttrValue(ShadowAssetManager.java:415)
at org.robolectric.shadows.ShadowResources.getOverlayedThemeValue(ShadowResources.java:295)
at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:134)
at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:51)
at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:489)
at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
at android.content.Context.obtainStyledAttributes(Context.java:472)
at android.view.View.__constructor__(View.java:3677)
at android.view.View.<init>(View.java)
```

The layout is very simple (empty).

```
 <?xml version="1.0" encoding="utf-8"?>
 <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
          android:orientation="vertical"
          android:layout_width="match_parent"
          android:layout_height="match_parent">

<TextView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:id="@+id/myId"/>
</LinearLayout>
```

The Test is only creating the activity.

```
@RunWith(CustomTestRunner.class)
@Config(constants = BuildConfig.class)
public class TestSimpleActivity
{
 @Test
public void test()
{
    SimpleActivity activity =  Robolectric.buildActivity(SimpleActivity.class).create().start().resume().visible().get();

    Assert.assertEquals(true, "test".equals("fail"));
}
}
```

Any ideas or suggestions?

**Comment by nenick** [comment]
Looks like there are issues with the styling. Did you add the shadow-v4 dependencies?

**Comment by misrakli** [comment]
Indeed the problem is the missing styling. I have a multimodule project setup, where all my business logic (activities, fragments) and presentation layer components (style, resources) are in a android library ('core' in your example), and a very thin app module for configuration of the core library.
In the app module i didn't have a `styles.xml`, in the app modules `AndroidManifest.xml` I set the style to a style defined in the core library. 
When i am now adding an Activity and a layout to the app module without defining a style in the app module, the tests don't run. This causes the `StringIndexOutOfBoundsException`.

When I am adding a `styles.xml` in the app module and set the parent of the style to style defined in the core library the tests are not running. There is an "endless loop" (waited 5 minutes) while trying to run the task `testDebug`, it doesnt finish.
Edit: After 7 min i got following exception: `java.lang.OutOfMemoryError: Java heap space`

After adding a `styles.xml` to the app module and changing the style in the apps `AndrodiManifest.xml` to the app modules style the test works.
But this is not the way i want to solve the problem, because the app should use the style defined in the core library module. Is this possible?

**Comment by nenick** [comment]
I can't reproduce it. I deleted the `style.xml` from the app module and did a `./gradlew clean app:test` and the tests run like expected. Best would be if your fork this project and show me how you have setup your styles to get this issue.

**Comment by misrakli** [comment]
I forked the project but cannot reproduce it for now, too. Maybe I have to add more and more "features" from my real project.The main difference i think is using the v4-support library.

**Comment by nenick** [comment]
Perhaps same issue like https://github.com/robolectric/robolectric/issues/1736 ?
